ECHO "Initrc for Kimi's OS" # Prints a string to the debug log
MODULE boot/idm.elf # Loads and executes a module located at the path
MODULE boot/part_mgr.elf
MODULE boot/ifsm.elf
# This is a comment
#     source file    dest  offset
# MOUNT /dev/disk/ide0 /home 0x1000 # this is hexadecimal
                          #  4096   this is decimal
                          #0010000  this is octal
MOUNT /dev/disk/ide0 /home
END # Ends the initrc. 
